from __future__ import annotations

import argparse
from pathlib import Path

from opencc import OpenCC


ROOT = Path(__file__).resolve().parents[1]


def has_cjk(word: str) -> bool:
    return any("\u4e00" <= ch <= "\u9fff" for ch in word)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=ROOT / "data" / "dict" / "nexaloid.tsv")
    parser.add_argument("--out", type=Path, default=ROOT / "data" / "dict" / "generated" / "traditional.generated.tsv")
    parser.add_argument("--limit", type=int, default=0, help="0 keeps all generated entries")
    args = parser.parse_args()

    cc = OpenCC("s2t")
    lines = args.source.read_text(encoding="utf-8").splitlines()
    rows: dict[str, tuple[float, str]] = {}

    for line in lines:
        parts = line.split()
        if len(parts) < 2:
            continue
        word = parts[0]
        if len(word) < 2 or not has_cjk(word):
            continue
        try:
            score = float(parts[1])
        except ValueError:
            continue
        pos = parts[2] if len(parts) > 2 else "n"
        traditional = cc.convert(word)
        if traditional != word:
            old = rows.get(traditional)
            if old is None or score > old[0]:
                rows[traditional] = (score, pos)

    sorted_rows = [(word, score, pos) for word, (score, pos) in rows.items()]
    sorted_rows.sort(key=lambda row: (-row[1], len(row[0]), row[0]))
    if args.limit > 0:
        sorted_rows = sorted_rows[: args.limit]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", encoding="utf-8", newline="\n") as f:
        f.write("# generated by tools/generate_traditional_overlay.py\n")
        for word, score, pos in sorted_rows:
            f.write(f"{word}\t{score:.8f}\t{pos}\n")
    print(f"wrote {len(sorted_rows)} entries to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
